name: kairo
description: "Production-ready Flutter Clean Architecture template."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8

  dartz: ^0.10.1
  dio: ^5.7.0
  drift: ^2.22.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  fl_chart: ^0.69.0
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  freezed_annotation: ^3.0.0

  go_router: ^14.8.1
  google_fonts: ^6.2.1
  intl: any
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  

  lottie: ^3.3.1
  path: ^1.9.0
  path_provider: ^2.1.5

  riverpod_annotation: ^2.6.1

 
  shared_preferences: ^2.3.5
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.28
  supabase_flutter: ^2.12.0
  timezone: ^0.10.0
  
  url_launcher: ^6.3.2
  uuid: ^4.5.1

    # Error Tracking & Analytics
  sentry_flutter: ^8.0.0

  # Social Authentication
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.5
  drift_dev: ^2.22.0
  
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  freezed: ^3.0.0
  json_serializable: ^6.9.4
  mocktail: ^1.0.4

  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/icon/
    - assets/images/
    - assets/icons/
    - assets/lottie/
